routes/web.php
<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\ActivityController;
use App\Http\Controllers\CollectiveController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\LeadController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductStoreController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\StoreController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\TutionController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/welcome');
});

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::get('/account/create', [AccountController::class,'create'])->name('accounts.create');
Route::post('/accounts/store', [AccountController::class,'store'])->name('accounts.store');
Route::get('/account/view', [AccountController::class,'view'])->name('accounts.view');
Route::get('/account/edit/{id}', [AccountController::class,'edit'])->name('accounts.edit');
Route::post('/account/update/{id}', [AccountController::class,'update'])->name('accounts.update');
Route::get('/account/delete/{id}', [AccountController::class,'delete'])->name('accounts.delete');
Route::get('/account/show/{id}', [AccountController::class,'show'])->name('accounts.show');
Route::get('/account/fetch', [AccountController::class,'fetchAccounts']);


Route::get('/contacts/create', [ContactController::class,'create'])->name('contacts.create');
Route::post('/contacts/store', [ContactController::class,'store'])->name('contacts.store');
Route::get('/contacts/view', [ContactController::class,'view'])->name('contacts.view');
Route::get('/contacts/edit/{id}', [ContactController::class,'edit'])->name('contacts.edit');
Route::post('/contacts/update/{id}', [ContactController::class,'update'])->name('contacts.update');
Route::get('/contacts/delete/{id}', [ContactController::class,'delete'])->name('contacts.delete');
Route::get('/contacts/show/{id}', [ContactController::class,'show'])->name('contacts.show');
Route::get('/contacts/fetch', [ContactController::class,'fetchContacts']);

Route::get('/activities/fetch', [ActivityController::class,'fetchActivities']);
Route::resource('/activities',ActivityController::class);

Route::get('/leads/fetch', [LeadController::class,'fetchLeads']);
Route::resource('/leads',LeadController::class);

Route::get('/stores/fetch', [StoreController::class,'fetchStores']);
Route::resource('/stores',StoreController::class);

Route::get('/products/fetch', [ProductController::class,'fetchProducts']);
Route::get('/products/detachproduct', [ProductController::class,'detachproduct']);
Route::resource('/products',ProductController::class);

Route::get('/projects/fetch', [ProjectController::class,'fetchProjects']);
Route::resource('/projects',ProjectController::class);

Route::get('/students/fetch', [StudentController::class,'fetchStudents']);
Route::resource('/students',StudentController::class);

Route::get('/tutions/fetch', [TutionController::class,'fetchTution']);
Route::resource('/tutions',TutionController::class);

Route::view('/test', 'Test1');

app/Models/Project.php
<?php

namespace App\Models;

use App\Models\Traits\HasUuid;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Project extends Model
{
    use HasFactory,HasUuid;
    protected $fillable=['name','implementation_status','priority','project_type','start_date','due_date','product','project_hosting_type'];

    public $incrementing = false;
    protected $keyType = 'string';

    public function activities(): HasMany
    {
        return $this->hasMany(Activity::class);
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Interfaces\ProjectRepositoryInterface;
use App\Models\Project;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ProjectController extends Controller
{
    protected ProjectRepositoryInterface $projectRepository;
    public function __construct(ProjectRepositoryInterface $projectRepository) {
        $this->projectRepository = $projectRepository;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('projects.index');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('projects.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // Project::create($request->all());
        $projects = $this->projectRepository->create($request);

        return redirect()->route('projects.index');


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $project = Project::find($id);
        $activities = $project->activities;

        return view('projects.show', compact('project','activities'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $projects = $this->projectRepository->update($id,$request);
        return redirect()->route('projects.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function fetchProjects(Request $request)
    {
        //
            return $this->projectRepository->fetchProjects($request);
    }
}

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="container">
                        <h4 class="mt-3">Product</h4>
                        {{ Form::open(['route' => ['projects.store']]) }}
                        {{ Form::token() }}
                            @include('projects.form')

                            <div class="mt-4 mb-2">

                                <button type="submit" class="btn btn-outline-primary mx-5">Save</button>
                                <a href="{{ route('projects.index') }}">
                                    <button type="button" class="btn btn-danger">Cancel</button>
                                </a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="container">
                        {{-- <form class="mb-3" id="update-form" method="POST" action="{{ route('activities.update', ['activity' => $activity->id]) }}"> --}}
                            {{  Form::model($product, ['route' => ['projects.update', $product->id]],['class'=>'mt-2','id'=>'update-form'])  }}
                            @method('PATCH')
                            {{ Form::token() }}
                            @include('projects.form')

                            <div class="mt-4 mb-4">

                                <button type="submit" id="update-button" class="btn btn-outline-primary mx-5">Save</button>

                                <a href='{{ route('projects.index') }}'>
                                    <button type="button" class="btn btn-danger">Cancel</button>
                                </a>
                            </div>
                            {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/projects/fetch.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">

                    <div class="container"style="width: 100%; overflow-x: auto;">
                        <a href="{{ route('projects.create') }}">Create lead</a>
                        <table class="table" >
                            <thead class="table-dark">
                                <th>Product ID</th>
                                <th>Name</th>

                            </thead>
                            <tbody>
                                <tr>
                                    <td></td>
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/projects/form.blade.php
<div class="row pt-3">
    <div class="form-group col-md-4">

        {{ Form::label('name', 'Product Name') }} @error('name')
            <div class="text-danger">{{ $message }}</div>
        @enderror
        {{ Form::text('name', null, ['class' => 'form-control']) }}

    </div>
    <div class="form-group col-md-4">
        {{  Form::label("implementation_status", "Implimentation Status")}}
        {{ Form::select('implementation_status', ['New'=>'New','Assign'=>'Assign','Inprocess'=>'Inprocess','Code Review'=>'Code Review','Merge Pending'=>'Merge Pending','Stage Realese'=>'Stage Realese','Completed'=>'Completed','On hold'=>'On hold','Customer Side Pending'=>'Customer Side Pending'], null, ['placeholder' => 'Select Implementation type','class' => 'form-select']) }}
    </div>


</div>

<div class="row pt-3">

    <div class="form-group col-md-4">
        {{ Form::label("priority", "Priority")}}@error('priority')
        <div class="text-danger">{{ $message }}</div>
    @enderror
        {{ Form::select('priority', ['Hign' => 'Hign', 'Medium' => 'Medium','Low'=>'Low'], null, ['placeholder' => 'Select Priority','class' => 'form-select']) }}

    </div>

    <div class="form-group col-md-4">

    {{ Form::label('project_type', 'Project Type') }}
    {{ Form::select('project_type',['Addon' => 'Addon', 'Fussion' => 'Fussion','Mobile Application'=>'Mobile Application', 'POC' => 'POC', 'R & D' => 'R & D', 'Free CRM' => 'Free CRM', 'Template' => 'Template', 'Optimize' => 'Optimize'], null , ['placeholder' => 'Select Project Type','class'=>'form-select']) }}

    </div>

</div>

<div class="row pt-3">

    <div class="form-group col-md-4">
        {{ Form::label("start_date", "Start Date")}}@error('start_date')
        <div class="text-danger">{{ $message }}</div>
    @enderror
        {{ Form::date('start_date', null,['class' => 'form-control date'] ) }}
    </div>
    <div class="form-group col-md-4">
        {{ Form::label("due_date", "Due Date")}}
        {{ Form::date('due_date', null,['class' => 'form-control date'] ) }}
    </div>

</div>

<div class="row pt-3">

    <div class="form-group col-md-4">
        {{ Form::label("product", "Product")}}
        {{ Form::select('product', ['Cloud Telephony' => 'Cloud Telephony','CRM' => 'CRM','CRM book Subcription'=>'CRM book Subcription','Enjay Latitude Lite' => 'Enjay Latitude Lite','Enjay Ensight' => 'Enjay Ensight','Enjay out mails' => 'Enjay out mails'], null , ['placeholder' => 'Select Priority','class'=>'form-select']) }}

    </div>

    <div class="form-group col-md-4">

    {{ Form::label('project_hosting_type', 'Project Hosting Type') }}
    {{ Form::select('project_hosting_type',['Enjay Cloud' => 'Enjay Cloud', 'On site' => 'On site','Internal Project'=>'Internal Project', 'Client Cloud' => 'Client Cloud'], null , ['placeholder' => 'Select Hosting Type','class'=>'form-select']) }}

    </div>

</div>

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('content')
    <script src="{{ asset('js/project.js') }}"></script>
    <style>
        .table-container {
            width: 100%;
            max-height: 500px;
            /* overflow: auto; */
        }
        th, td { white-space: nowrap;}
        tr { height: 50px;}


    </style>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <a href="{{ route('projects.create') }}" class="px-3 py-3">Add Project</a>
                    <div class="table-container">
                        <table id="table" class="table hover">
                            <thead class="table-dark">
                                <th>Project Name</th>
                                <th>Priority</th>
                                <th>project Type</th>
                                <th>Start Date</th>
                                <th>Due Date</th>

                            </thead>
                            <tbody id="contact-list">

                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>

                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/projects/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="container">

                        <h4 class="mt-3">Project Detail view</h4>
                        <table class="table table-borderless">
                            <tbody>


                                <tr>
                                    <td>Project Name</td>
                                    <td>{{ $project->name }}</td>
                                </tr>
                                <tr>
                                    <td>Implementation Status</td>
                                    <td>{{ $project->implementation_status }}</td>
                                </tr>
                                <tr>
                                    <td>Priority</td>
                                    <td>{{ $project->priority }}</td>
                                </tr>
                                <tr>
                                    <td>Project Type</td>
                                    <td>{{ $project->project_type }}</td>
                                </tr>
                                <tr>
                                    <td>Start Date</td>
                                    <td>{{ $project->start_date }}</td>
                                </tr>
                                <tr>
                                    <td>Due date</td>
                                    <td>{{ $project->due_date }}</td>
                                </tr>
                                <tr>
                                    <td>Product</td>
                                    <td>{{ $project->product }}</td>
                                </tr>                                <tr>
                                    <td>Project Hosting Type</td>
                                    <td>{{ $project->project_hosting_type }}</td>
                                </tr>

                            </tbody>
                        </table>



                        <a href="{{ route('projects.edit', ['project' => $project->id]) }}">
                            <button class="btn btn-primary mx-2 mb-3">Edit</button>
                        </a>
                        <a href="{{ route('projects.index') }}">
                            <button class="btn btn-secondary mx-2 mb-3">Cancel</button>
                        </a>
                        <a href="{{ route('projects.destroy', ['project' => $project->id]) }}">
                            <button class="btn btn-danger mx-2 mb-3">Delete</button>
                        </a>

                        <table class="table table-borderless mt-2">

                            <tbody>
                                <tr>
                                    <td><h3>All Activities</h3></td>
                                </tr>
                                {{-- @dd($activities) --}}
                                @foreach ($activities as $activity )
                                <tr>
                                    <td>Name</td>
                                    <td><a href="{{ route('activities.show',['activity'=>$activity->id]) }}">{{ $activity->subject }}</a></td>

                                </tr>
                                @endforeach

                            </tbody>
                        </table>

                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection