routes/web.php
<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\ActivityController;
use App\Http\Controllers\CollectiveController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\LeadController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductStoreController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\StoreController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\TutionController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/welcome');
});

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::get('/account/create', [AccountController::class,'create'])->name('accounts.create');
Route::post('/accounts/store', [AccountController::class,'store'])->name('accounts.store');
Route::get('/account/view', [AccountController::class,'view'])->name('accounts.view');
Route::get('/account/edit/{id}', [AccountController::class,'edit'])->name('accounts.edit');
Route::post('/account/update/{id}', [AccountController::class,'update'])->name('accounts.update');
Route::get('/account/delete/{id}', [AccountController::class,'delete'])->name('accounts.delete');
Route::get('/account/show/{id}', [AccountController::class,'show'])->name('accounts.show');
Route::get('/account/fetch', [AccountController::class,'fetchAccounts']);


Route::get('/contacts/create', [ContactController::class,'create'])->name('contacts.create');
Route::post('/contacts/store', [ContactController::class,'store'])->name('contacts.store');
Route::get('/contacts/view', [ContactController::class,'view'])->name('contacts.view');
Route::get('/contacts/edit/{id}', [ContactController::class,'edit'])->name('contacts.edit');
Route::post('/contacts/update/{id}', [ContactController::class,'update'])->name('contacts.update');
Route::get('/contacts/delete/{id}', [ContactController::class,'delete'])->name('contacts.delete');
Route::get('/contacts/show/{id}', [ContactController::class,'show'])->name('contacts.show');
Route::get('/contacts/fetch', [ContactController::class,'fetchContacts']);

Route::get('/activities/fetch', [ActivityController::class,'fetchActivities']);
Route::resource('/activities',ActivityController::class);

Route::get('/leads/fetch', [LeadController::class,'fetchLeads']);
Route::resource('/leads',LeadController::class);

Route::get('/stores/fetch', [StoreController::class,'fetchStores']);
Route::resource('/stores',StoreController::class);

Route::get('/products/fetch', [ProductController::class,'fetchProducts']);
Route::get('/products/detachproduct', [ProductController::class,'detachproduct']);
Route::resource('/products',ProductController::class);

Route::get('/projects/fetch', [ProjectController::class,'fetchProjects']);
Route::resource('/projects',ProjectController::class);

Route::get('/students/fetch', [StudentController::class,'fetchStudents']);
Route::resource('/students',StudentController::class);

Route::get('/tutions/fetch', [TutionController::class,'fetchTution']);
Route::resource('/tutions',TutionController::class);

Route::view('/test', 'Test1');

app/Models/Student.php
<?php

namespace App\Models;

use App\Models\Traits\HasUuid;
use App\Traits\RelationTraits;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Student extends Model
{
    use HasFactory, HasUuid,RelationTraits;
    protected $fillable =['name','gender','dob','contact','guardian_name','guardian_contact','class','year','department','address'];


    public $incrementing = false;
    protected $keyType = 'string';

    public function tutions()
    {
        return $this->belongsToMany(Tution::class,'student_tution','student_id','tution_id');
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Interfaces\StudentRepositoryInterface;
use App\Models\Student;
use App\Traits\RelationTraits;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class StudentController extends Controller
{
    use RelationTraits;
    protected StudentRepositoryInterface $studentRepository;
    public function __construct(StudentRepositoryInterface $studentRepository) {
        $this->studentRepository = $studentRepository;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('students.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $tutions = DB::table('tutions')->pluck('name', 'id');
        $tution = $tutions->toArray();
        return view('students.create',compact('tution'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // $tution = $request->input('tutions');
        // $student = Student::create($request->all());
        // $student->tutions()->attach($tution);
        $students = $this->studentRepository->create($request);
        return redirect()->route('students.index');


        //
        // $tution = $request->input('products');
        // $student = Student::create($request->all());
        // $student->tutions()->attach($tution);

        // return redirect()->route('students.index');

        // $product = $request->input('products');
        // $store = Store::create($request->all());
        // $store->products()->attach($product);
        // return redirect()->route('stores.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $student = Student::find($id);
        $tutions = $student->tutions;
        return view('students.show', compact('student','tutions'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        //
        $student = Student::find($id);
        $tutions = DB::table('tutions')->pluck('name', 'id');
        $tution = $tutions->toArray();
        if (is_null($student && $tution)) {
            return redirect()->back();
        } else {
            return view('students.edit', compact('student', 'tution'));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //

        // $student = Student::find($id);
        // $student->update($request->all());
        // $tution = $request->input('tutions');
        // $student->tutions()->attach($tution);
        // $this->attachTution($request, $id);
        // $this->studentRepository->update($id,$request);
        $students = $this->studentRepository->update($id,$request);
        return redirect()->route('students.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        // Student::find($id)->delete();
        $students = $this->studentRepository->delete($id);

        return redirect()->route('students.index');
    }
    public function fetchStudents(Request $request)
    {

        return $this->studentRepository->fetchStudents($request);

    }
    public function detachproduct(Request $request)
    {
        $request = request()->all();
        $product_id=$request['product_Id'];
        $store_id=$request['store_Id'];
        $model=$request['model'];
        $function_name=$request['function_name'];

        // $product = $model::find($product_id);
        // $product->$function_name->detach($store_id);

        // $data=[
        //     'store_id'=>$store_id,
        //     'product_id'=>$product_id,
        // ];
        return response()->json(['message'=>'success']);
        // return response()->json(['store_id'=>$store_id,'product_id'=>$product_id,]);
    }
}

resources/views/students/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="container">
                        <h4 class="mt-3">Student</h4>
                        {{ Form::open(['route' => ['students.store']]) }}
                        {{ Form::token() }}
                            @include('students.form')

                            <div class="mt-4 mb-2">

                                <button type="submit" class="btn btn-outline-primary mx-5">Save</button>
                                <a href="{{ route('students.index') }}">
                                    <button type="button" class="btn btn-danger">Cancel</button>
                                </a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/students/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="container">
                        <h4 class="mt-3">Edit Student</h4>
                        {{  Form::model($student, ['route' => ['students.update', $student->id]],['class'=>'mt-2','id'=>'update-form'])  }}
                            @method('PATCH')
                            {{ Form::token() }}
                            @include('students.form')

                            <div class="mt-4 mb-4">

                                <button type="submit" id="update-button" class="btn btn-outline-primary mx-5">Save</button>

                                <a href='{{ route('students.index') }}'>
                                    <button type="button" class="btn btn-danger">Cancel</button>
                                </a>
                            </div>
                            {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/students/fetch.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">

                    <div class="container"style="width: 100%; overflow-x: auto;">
                        <a href="{{ route('stores.create') }}">Create store</a>
                        <table class="table" >
                            <thead class="table-dark">
                                <th>Store ID</th>
                                <th>Name</th>

                            </thead>
                            <tbody>
                                @foreach ($stores as $store)
                                <tr>
                                    <td></td>
                                    <td></td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/students/form.blade.php
@foreach (@config('layouts.student.edit') as $fields)

    <div class="row">

        @foreach ($fields as $field)
            <div class="col pt-3">
                @foreach ($field as $item)
                    @include('fields.' . $item['type'], $item)
                @endforeach
            </div>
        @endforeach

    </div>
@endforeach


{{-- <div class="row pt-3">
    <div class="form-group col-md-4">

        {{ Form::label('student_name', 'Student Name') }} @error('student_name')
            <div class="text-danger">{{ $message }}</div>
        @enderror
        {{ Form::text('student_name', null, ['class' => 'form-control']) }}

    </div>
    <div class="form-group col-md-4">
        {{ Form::label('gender', 'Gender') }}
        <div class="form-check-group">
            {{ Form::radio('gender', 'Male'), null, ['class' => 'form-check-input'] }}
            {{ Form::label('gender', 'Male') }}

            {{ Form::radio('gender', 'Female'), null, ['class' => 'form-check-input'] }}
            {{ Form::label('gender', 'Female') }}


            {{ Form::radio('gender', 'Other'), null, ['class' => 'form-check-input'] }}
            {{ Form::label('gender', 'Other') }}
        </div>
    </div>
</div>

<div class="row pt-3">
    <div class="form-group col-md-4">
        {{ Form::label('tutions', 'Tution') }}
        {{ Form::select('tutions[]', $tution , null, ['placeholder' => 'Select Tution', 'class' => 'form-select' ,'multiple'=>'multiple']) }}

    </div>
</div>


<div class="row pt-3">

    <div class="form-group col-md-4">
        {{ Form::label("dob", "Date of birth")}}
        {{ Form::date('dob', null,['class' => 'form-control'] ) }}

    </div>

    <div class="form-group col-md-4">
        {{ Form::label("contact", "Contact")}}
        {{ Form::number('contact', null , $attributes = ['class' => 'form-control']) }}

    </div>

</div>

<div class="row pt-3">

    <div class="form-group col-md-4">
        {{ Form::label("guardian_name", "Gurdian Name")}}
        {{ Form::text('guardian_name', null,['class' => 'form-control'] ) }}

    </div>

    <div class="form-group col-md-4">
        {{ Form::label("guardian_contact", "Gurdian Contact")}}
        {{ Form::number('guardian_contact', null , $attributes = ['class' => 'form-control']) }}

    </div>

</div>

<div class="row pt-3">

    <div class="form-group col-md-4">

        {{ Form::label('class', 'Class Name') }}
        {{ Form::select('class', ['Bcom'=>'Bcom','Mcom'=>'Mcom','BA'=>'BA','MA'=>'MA','BSC'=>'BSC','MSC'=>'MSC','BCA'=>'BCA', 'MCA'=>'MCA','BE'=>'BE', 'ME'=>'ME' ,'B-Tec'=>'B-Tec','M-Tec'=>'M-tech'] ,null, ['class' => 'form-select','placeholder'=>'Select Class']) }}

    </div>
    <div class="form-group col-md-4">

        {{ Form::label('year', 'Class Year') }}
        {{ Form::select('year', ['First Year'=>'First Year','Second Year'=>'Second Year','Third Year'=>'Third Year','Forth Year'=>'Forth Year','Fifth Year'=>'Fifth Year','Sixth Year'=>'Sixth Year'] ,null, ['class' => 'form-select','placeholder'=>'Select Year']) }}

    </div>

</div>

<div class="row pt-3">

    <div class="form-group col-md-4">

        {{ Form::label('department', 'Deapartment Name') }}
        {{ Form::select('department', ['Arts'=>'Arts','Commerce'=>'Commerce','Science'=>'Science','Engineering'=>'Engineering','Pharmacy'=>'Pharmacy','Medical'=>'Medical','Other'=>'Other'] ,null, ['class' => 'form-select','placeholder'=>'Select Department']) }}

    </div>
    <div class="form-group col-md-4">

        {{ Form::label('address', 'Address') }}
        {{ Form::textarea('address', null ,$attributes = ['class'=>'form-control','rows'=>3]); }}

    </div>

</div> --}}

resources/views/students/index.blade.php
@extends('layouts.app')

@section('content')
    <script src="{{ asset('js/student.js') }}"></script>
    <style>
        .table-container {
            width: 100%;
            max-height: 500px;
            /* overflow: auto; */
        }
        th, td { white-space: nowrap;}
        tr { height: 50px;}


    </style>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <a href="{{ route('students.create') }}" class="px-3 py-3">Add Student</a>
                    <div class="table-container">
                        <table id="table" class="table hover">
                            <thead class="table-dark">
                                <th>Student Name</th>
                                <th>Gender</th>
                                <th>Birth Date</th>
                                <th>Contact</th>
                                <th>Class</th>
                                <th>Year</th>
                                <th>Department</th>

                            </thead>
                            <tbody id="contact-list">

                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>

                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/students/show.blade.php
@extends('layouts.app')

@section('content')
<script src="{{ asset('js/productdetach.js') }}"></script>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="container ">

                        <h4 class="mt-3">Detail view</h4>
                        <table class="table table-borderless">
                            <tbody>

                                <tr>
                                    <td>Student Name</td>
                                    <td>{{ $student->name }}</td>
                                </tr>
                                <tr>
                                    <td>Gender</td>
                                    <td>{{ $student->gender }}</td>
                                </tr>
                                <tr>
                                    <td>Date of Birth</td>
                                    <td>{{ $student->dob }}</td>
                                </tr>
                                <tr>
                                    <td>Contact</td>
                                    <td>{{ $student->contact }}</td>
                                </tr>
                                <tr>
                                    <td>Gurdian Name</td>
                                    <td>{{ $student->guardian_name }}</td>
                                </tr>
                                <tr>
                                    <td>Gurdian Contact</td>
                                    <td>{{ $student->guardian_contact }}</td>
                                </tr>
                                <tr>
                                    <td>Class</td>
                                    <td>{{ $student->class }}</td>
                                </tr><tr>
                                    <td>Year</td>
                                    <td>{{ $student->year }}</td>
                                </tr>
                                <tr>
                                    <td>Department</td>
                                    <td>{{ $student->department }}</td>
                                </tr><tr>
                                    <td>Address</td>
                                    <td>{{ $student->address }}</td>
                                </tr>

                            </tbody>
                        </table>

                            <input type="hidden" id="hidden" name="relation_ship" value="{{ $student->id }}" />
                            <input type="hidden" id="model" name="model" value="Student" />
                            <input type="hidden" id="function_name" name="function_name" value="tutions" />

                            <a href="{{ route('students.edit',['student'=>$student->id]) }}">
                                <button class="btn btn-primary mx-2 mb-3">Edit</button>
                            </a>
                            <a href="{{ route('students.index') }}">
                                <button class="btn btn-secondary mx-2 mb-3">Cancel</button>
                            </a>
                            <a>
                            <form action="{{ route('students.destroy', ['student' => $student->id]) }}" method="POST">
                                @csrf
                                @method('DELETE')

                                <button type="submit" class="btn btn-danger mx-2 mb-3">Delete</button>
                            </form>
                        </a>
                        <table class="table table-borderless mt-2">

                            <tbody>
                                <tr>
                                    <td>
                                        <h3>All Tutions</h3>
                                    </td>
                                </tr>
                                @foreach ($tutions as $tution)
                                    <tr>
                                        <td>Tution Name</td>
                                        <td>
                                        {{-- <td><a href="{{ route('stores.show', ['store' => $store->id]) }}" class="store-link">{{ $store->name }}</a> --}}
                                            <a href="{{ route('tutions.show', ['tution' => $tution->id]) }}" class="store-link" >{{ $tution->name }}</a>

                                        </td>
                                        <td>

                                        <button class="myButton btn btn-danger" id="myButton" data-child-id="{{ $tution->id }}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"/>
                                            <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"/>
                                          </svg></button>



                                        </td>
                                    </tr>
                                @endforeach



                            </tbody>
                        </table>

                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection