routes/web.php
<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\ActivityController;
use App\Http\Controllers\CollectiveController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\LeadController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductStoreController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\StoreController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\TutionController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/welcome');
});

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::get('/account/create', [AccountController::class,'create'])->name('accounts.create');
Route::post('/accounts/store', [AccountController::class,'store'])->name('accounts.store');
Route::get('/account/view', [AccountController::class,'view'])->name('accounts.view');
Route::get('/account/edit/{id}', [AccountController::class,'edit'])->name('accounts.edit');
Route::post('/account/update/{id}', [AccountController::class,'update'])->name('accounts.update');
Route::get('/account/delete/{id}', [AccountController::class,'delete'])->name('accounts.delete');
Route::get('/account/show/{id}', [AccountController::class,'show'])->name('accounts.show');
Route::get('/account/fetch', [AccountController::class,'fetchAccounts']);


Route::get('/contacts/create', [ContactController::class,'create'])->name('contacts.create');
Route::post('/contacts/store', [ContactController::class,'store'])->name('contacts.store');
Route::get('/contacts/view', [ContactController::class,'view'])->name('contacts.view');
Route::get('/contacts/edit/{id}', [ContactController::class,'edit'])->name('contacts.edit');
Route::post('/contacts/update/{id}', [ContactController::class,'update'])->name('contacts.update');
Route::get('/contacts/delete/{id}', [ContactController::class,'delete'])->name('contacts.delete');
Route::get('/contacts/show/{id}', [ContactController::class,'show'])->name('contacts.show');
Route::get('/contacts/fetch', [ContactController::class,'fetchContacts']);

Route::get('/activities/fetch', [ActivityController::class,'fetchActivities']);
Route::resource('/activities',ActivityController::class);

Route::get('/leads/fetch', [LeadController::class,'fetchLeads']);
Route::resource('/leads',LeadController::class);

Route::get('/stores/fetch', [StoreController::class,'fetchStores']);
Route::resource('/stores',StoreController::class);

Route::get('/products/fetch', [ProductController::class,'fetchProducts']);
Route::get('/products/detachproduct', [ProductController::class,'detachproduct']);
Route::resource('/products',ProductController::class);

Route::get('/projects/fetch', [ProjectController::class,'fetchProjects']);
Route::resource('/projects',ProjectController::class);

Route::get('/students/fetch', [StudentController::class,'fetchStudents']);
Route::resource('/students',StudentController::class);

Route::get('/tutions/fetch', [TutionController::class,'fetchTution']);
Route::resource('/tutions',TutionController::class);

Route::view('/test', 'Test1');

app/Models/Product.php
<?php

namespace App\Models;

use App\Models\Traits\HasUuid;
use App\Traits\DetachTrait;
use App\Traits\RelationTraits;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory,HasUuid, RelationTraits;

    protected $fillable = ['id','name','category','brand','price'];

    public $incrementing = false;
    protected $keyType = 'string';

    public function stores()
    {
        return $this->belongsToMany(Store::class,'product_store', 'product_id', 'store_id');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Interfaces\ProductRepositoryInterface;
use App\Models\Product;
use App\Models\Student;
use App\Models\Store;
use App\Traits\RelationTraits;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class ProductController extends Controller
{
    use RelationTraits;
    protected ProductRepositoryInterface $productRepository;
    public function __construct(ProductRepositoryInterface $productRepository) {
        $this->productRepository = $productRepository;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('products.index');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $store =DB::table('stores')->pluck('name','id');
        $stores = $store->toArray();
        // $stores = Store::select('id','name')->get()->pluck('name','id');
        // dd($stores);
        return view('products.create',compact('stores'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        // $store = $request->input('stores');
        // $product = Product::create($request->all());
        // $product->stores()->attach($store);
        $products = $this->productRepository->create($request);

        return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $product = Product::find($id);
        $stores = $product->stores;
        // dd($stores->toArray());
        return view('products.show', compact('product','stores'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product=Product::find($id);
        $moduleName = "Product";
        if (is_null($product)) {
            return redirect()->back();
        } else {
            return view('products.edit', compact('product','moduleName'));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {

        $products = $this->productRepository->update($id,$request);
        return redirect()->route('products.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        // Product::find($id)->delete();
        $products = $this->productRepository->delete($id);

        return redirect()->route('products.index');
    }

    public function fetchProducts(Request $request)
    {
        //

        return $this->productRepository->fetchProducts($request);
    }

    public function detachproduct (Request $request)
    {
        $request = request()->all();
        $parent_Id=$request['parent_Id'];
        $child_Id=$request['child_Id'];
        $Model=$request['model'];
        $Function_Name=$request['function_name'];
        $modelClass = 'App\\Models\\' . $Model;
        $detach = $modelClass::find($parent_Id);
        $detach->$Function_Name()->detach($child_Id);

        // $data=[
        //     'child_Id'=>$child_Id,
        //     'parent_Id'=>$parent_Id,
        //     'model'=>$Model,
        //     'function_name'=>$Function_Name
        // ];
        return response()->json($request);
        // return response()->json(['child_Id'=>$child_Id,'parent_Id'=>$parent_Id,]);

    }
}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="container">
                        <h4 class="mt-3">Product</h4>
                        {{ Form::open(['route' => ['products.store']]) }}
                        {{ Form::token() }}
                            @include('products.form')

                            <div class="mt-4 mb-2">

                                <button type="submit" class="btn btn-outline-primary mx-5">Save</button>
                                <a href="{{ route('products.index') }}">
                                    <button type="button" class="btn btn-danger">Cancel</button>
                                </a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="container">
                        {{-- <form class="mb-3" id="update-form" method="POST" action="{{ route('activities.update', ['activity' => $activity->id]) }}"> --}}
                            {{  Form::model($product, ['route' => ['products.update', $product->id]],['class'=>'mt-2','id'=>'update-form'])  }}
                            @method('PATCH')
                            {{ Form::token() }}
                            @include('products.form')

                            <div class="mt-4 mb-4">

                                <button type="submit" id="update-button" class="btn btn-outline-primary mx-5">Save</button>

                                <a href='{{ route('products.index') }}'>
                                    <button type="button" class="btn btn-danger">Cancel</button>
                                </a>
                            </div>
                            {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/products/fetch.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">

                    <div class="container"style="width: 100%; overflow-x: auto;">
                        <a href="{{ route('products.create') }}">Create lead</a>
                        <table class="table table-striped" >
                            <thead class="table-dark">
                                {{-- <th>Product ID</th> --}}
                                <th>Name</th>

                            </thead>
                            <tbody>
                                @foreach ($products as $product)
                                <tr>
                                    {{-- <td></td> --}}
                                    <td></td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/products/form.blade.php
@foreach (@config('layouts.product.edit') as $fields)

    <div class="row">
        @foreach ($fields as $field)
            <div class="col pt-3">
                @foreach ($field as $item)
                    @include('fields.' . $item['type'], $item)
                @endforeach
            </div>
        @endforeach

    </div>
@endforeach



{{-- <div class="row pt-3">
    <div class="form-group col-md-4">

        {{ Form::label('name', 'Product Name') }} @error('name')
            <div class="text-danger">{{ $message }}</div>
        @enderror
        {{ Form::text('name', null, ['class' => 'form-control']) }}

    </div>
    <div class="form-group col-md-4">
        {{  Form::label("stores", "Select Store")}}
        {{ Form::select('stores', $stores, null, ['class' => 'form-select', 'multiple'  ]) }}
    </div>
</div>

<div class="row pt-3">

    <div class="form-group col-md-4">
        {{ Form::label("category", "Product Category")}}
        {{ Form::select('category', ['Coldrinks' => 'Coldrinks', 'Fruits' => 'Fruits','Grocery'=>'Grocery','Milk Product'=>'Milk Product','Other'=>'Other'], null , ['placeholder' => 'Select Product Category','class'=>'form-control']) }}

    </div>

    <div class="form-group col-md-4">

    {{ Form::label('brand', 'Brand Name') }}
    {{ Form::text('brand', null, ['class' => 'form-control']) }}

    </div>

</div>

<div class="row pt-3">

    <div class="form-group col-md-4">
        {{ Form::label("price", "Product price")}}
        {{ Form::number('price', null, ['class' => 'form-control']) }}
    </div>

</div> --}}

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
    <script src="{{ asset('js/product.js') }}"></script>
    <style>
        .table-container {
            width: 100%;
            max-height: 500px;
            /* overflow: auto; */
        }
        th, td { white-space: nowrap;}
        tr { height: 50px;}


    </style>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <a href="{{ route('products.create') }}" class="px-3 py-3">Add Product</a>
                    <div class="table-container">
                        <table id="table" class="table hover ">
                            <thead class="table-dark">
                                {{-- <th>Product ID</th> --}}
                                <th>Product Name</th>
                                <th>Category</th>
                                <th>Brand</th>
                                <th>Price</th>

                            </thead >
                            <tbody id="contact-list">

                                <tr>
                                    {{-- <td></td> --}}
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>

                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')

    <script src="{{ asset('js/productdetach.js') }}"></script>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="container">

                        <h4 class="mt-3">Detail view</h4>
                        <table class="table table-borderless">
                            <tbody>

                                <tr>
                                    <td>Product Name</td>
                                    <td>{{ $product->name }}</td>
                                </tr>
                                <tr>
                                    <td>Product Category</td>
                                    <td>{{ $product->category }}</td>
                                </tr>
                                <tr>
                                    <td>Product Brand</td>
                                    <td>{{ $product->brand }}</td>
                                </tr>
                                <tr>
                                    <td>Product Price</td>
                                    <td>{{ $product->price }}</td>
                                </tr>

                            </tbody>
                        </table>


                        <input type="hidden" id="hidden" name="relation_ship" value="{{ $product->id }}" />
                        <input type="hidden" id="model" name="model" value="Product" />
                        <input type="hidden" id="function_name" name="function_name" value="stores" />
                        <a href="{{ route('products.edit', ['product' => $product->id]) }}">
                            <button class="btn btn-primary mx-2 mb-3">Edit</button>
                        </a>
                        <a href="{{ route('products.index') }}">
                            <button class="btn btn-secondary mx-2 mb-3">Cancel</button>
                        </a>
                        <form action="{{ route('products.destroy', ['product' => $product->id]) }}" method="POST">
                            @csrf
                            @method('DELETE')

                            <button type="submit" class="btn btn-danger mx-2 mb-3">Delete</button>
                        </form>

                        <table class="table table-borderless mt-2">

                            <tbody>
                                <tr>
                                    <td>
                                        <h3>All Store</h3>
                                    </td>
                                </tr>
                                @foreach ($stores as $store)
                                    <tr>
                                        <td>Store Name</td>
                                        <td>
                                        {{-- <td><a href="{{ route('stores.show', ['store' => $store->id]) }}" class="store-link">{{ $store->name }}</a> --}}
                                            <a href="{{ route('stores.show', ['store' => $store->id]) }}" class="store-link">{{ $store->name }}</a>

                                        </td>
                                        <td>

                                        <button class="myButton btn btn-danger" id="myButton" data-child-id="{{ $store->id }}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"/>
                                            <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"/>
                                          </svg></button>



                                        </td>
                                    </tr>
                                @endforeach



                            </tbody>
                        </table>

                    </div>

                </div>
            </div>
        </div>
    </div>

@endsection