routes/web.php
<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\ActivityController;
use App\Http\Controllers\CollectiveController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\LeadController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductStoreController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\StoreController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\TutionController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/welcome');
});

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::get('/account/create', [AccountController::class,'create'])->name('accounts.create');
Route::post('/accounts/store', [AccountController::class,'store'])->name('accounts.store');
Route::get('/account/view', [AccountController::class,'view'])->name('accounts.view');
Route::get('/account/edit/{id}', [AccountController::class,'edit'])->name('accounts.edit');
Route::post('/account/update/{id}', [AccountController::class,'update'])->name('accounts.update');
Route::get('/account/delete/{id}', [AccountController::class,'delete'])->name('accounts.delete');
Route::get('/account/show/{id}', [AccountController::class,'show'])->name('accounts.show');
Route::get('/account/fetch', [AccountController::class,'fetchAccounts']);


Route::get('/contacts/create', [ContactController::class,'create'])->name('contacts.create');
Route::post('/contacts/store', [ContactController::class,'store'])->name('contacts.store');
Route::get('/contacts/view', [ContactController::class,'view'])->name('contacts.view');
Route::get('/contacts/edit/{id}', [ContactController::class,'edit'])->name('contacts.edit');
Route::post('/contacts/update/{id}', [ContactController::class,'update'])->name('contacts.update');
Route::get('/contacts/delete/{id}', [ContactController::class,'delete'])->name('contacts.delete');
Route::get('/contacts/show/{id}', [ContactController::class,'show'])->name('contacts.show');
Route::get('/contacts/fetch', [ContactController::class,'fetchContacts']);

Route::get('/activities/fetch', [ActivityController::class,'fetchActivities']);
Route::resource('/activities',ActivityController::class);

Route::get('/leads/fetch', [LeadController::class,'fetchLeads']);
Route::resource('/leads',LeadController::class);

Route::get('/stores/fetch', [StoreController::class,'fetchStores']);
Route::resource('/stores',StoreController::class);

Route::get('/products/fetch', [ProductController::class,'fetchProducts']);
Route::get('/products/detachproduct', [ProductController::class,'detachproduct']);
Route::resource('/products',ProductController::class);

Route::get('/projects/fetch', [ProjectController::class,'fetchProjects']);
Route::resource('/projects',ProjectController::class);

Route::get('/students/fetch', [StudentController::class,'fetchStudents']);
Route::resource('/students',StudentController::class);

Route::get('/tutions/fetch', [TutionController::class,'fetchTution']);
Route::resource('/tutions',TutionController::class);

Route::view('/test', 'Test1');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.js"></script>


    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">


    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('DataTables/datatable-custom.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.css" />



</head>

<body class="bg-">
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-light shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ route('home') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    @if (Auth::check())

                    <ul class="navbar-nav me-auto">
                        <li>
                            <a class="nav-link"href="{{ route('accounts.view') }}">{{ __('Accounts') }}</a>
                        </li>
                        <li>
                            <a class="nav-link"href="{{ route('contacts.view') }}">{{ __('Contacts') }}</a>
                        </li>
                        <li>
                            <a class="nav-link"href="{{ route('activities.index') }}">{{ __('Activities') }}</a>
                        </li>
                        <li>
                            <a class="nav-link"href="{{ route('leads.index') }}">{{ __('Leads') }}</a>
                        </li>
                        </li>
                        <li>
                            <a class="nav-link"href="{{ route('products.index') }}">{{ __('Products') }}</a>
                        </li>
                        </li>
                        <li>
                            <a class="nav-link"href="{{ route('stores.index') }}">{{ __('Stores') }}</a>
                        </li>
                        <li>
                            <a class="nav-link"href="{{ route('projects.index') }}">{{ __('Projects') }}</a>
                        </li>
                        <li>
                            <a class="nav-link"href="{{ route('students.index') }}">{{ __('Students') }}</a>
                        </li>
                        <li>
                            <a class="nav-link"href="{{ route('tutions.index') }}">{{ __('Tutions') }}</a>
                        </li>
                    </ul>
                    @endif

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                        onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>

</html>